apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: observability
spec:
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.16.0 # Use the latest version of the operator
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    operator:
      enabled: true
    autoInstrumentation:
      enabled: true
    deployment:
      replicas: 1

