apiVersion: v1
kind: Service
metadata:
  name: grafana-ext
  namespace: observability
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

