apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: observability
spec:
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: observability
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  type: LoadBalancer  # Change this from ClusterIP to LoadBalancer
---


