apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-operator-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: opentelemetry-operator-group
  namespace: opentelemetry-operator-system
spec:
  targetNamespaces:
    - opentelemetry-operator-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  channel: stable
  name: opentelemetry-operator
  source: community-operators
  sourceNamespace: openshift-marketplace  # For k3s you may need to change this to `olm` or appropriate CatalogSource

